Repository Financial-Times/o-typography, pull requests merged in 2020-05, with the labels that each got.

#265 remove npm dependencies, which are a deviation from the spec :o
  package.json
Labels: bug, release:patch

#270 Ensure we only use a version of o-fonts which has the woff2 fonts
  bower.json
Labels: release:minor

#271 Add Github Action to apply Origami type label
  .github/workflows/apply-labels.yml
Labels: component
